lightning_module:
  _target_: sidon.model.flow_dialogue_sidon.lightning_module.FlowDialogueLatentSidon
  _recursive_: false

cfg:
  vae_checkpoint_path: /work/gj18/e43001/github.com/Sidon/sidon/mxve9r3f/checkpoints/epoch=0-step=490000.ckpt
  flow_model:
    sample_size: 1000
    in_channels: 32
    cross_attention_input_dim: 1024
    out_channels: 32
    num_layers: 12
    num_attention_heads: 12
    num_key_value_attention_heads: 6
  ssl_model_name: facebook/w2v-bert-2.0

  optim:
    lr: 1e-4
    weight_decay: 0.01
